### ISSUE TITLE
Proposal: Pool chart design change

### ISSUE THREAD

**Issue by pypper** [turtlecoin/block-explorer#33]
Currently, looks like so:

![screenshot from 2018-03-30 14-04-32](https://user-images.githubusercontent.com/33644581/38148332-fae85d32-3423-11e8-9cf5-064c5a982138.png)

Proposed change does the following:

 - title change, more accurate
 - better font choices for legibility
 - move legend to bottom
 - switch from pie -> donut. IMO the negative space makes it easier to look at the smaller slices of data.

### v1 no revisions
![screenshot from 2018-03-30 14-15-01](https://user-images.githubusercontent.com/33644581/38148499-c401b83a-3424-11e8-8b85-d9577531f90f.png)

### v2 revised based on @derp-derp-derp 's comments.
![screenshot from 2018-03-30 15-33-55](https://user-images.githubusercontent.com/33644581/38151174-3349dabe-3430-11e8-91cb-9afc853297ec.png)

## notes 

Looking for feedback or other ideas on improving this before I submit a PR, wasted pushing/pulling when iterating on the design. I have the proposed changes pushed to my explorer at https://explorer.trtlpwr.cc/#pools

## other notes

other graph types don't cut it well with this library beyond `pie` and `doughnut` with our dataset. with Soregums we tried stacked bar, and personally I tried `bar`, `radar`, & `polarArea`.

**Comment by ZedPea** [comment]
Looks wayyyy better imo :+1:

**Comment by SoreGums** [comment]
also font is a lot cleaner and legible - cringe every time looking at the old one now 😈

**Comment by derp-derp-derp** [comment]
perhaps order the list of pools desc by their share of hashrate, and also adjust the palette for additional contrast - right now there are too many greens imo

**Comment by pypper** [comment]
pools are listed desc by their hashrate in the legend.

i'll see what I can do about adding variance to the colors. they're based a hash of the name of the pool, but there are some tweaks I can make.

**Comment by pypper** [comment]
made a tweak to the hash function to make differences in the strings more dramatic in terms of color, should be a bit more of a spread now.

![screenshot from 2018-03-30 15-33-55](https://user-images.githubusercontent.com/33644581/38151082-caeea0da-342f-11e8-8fdf-01002bc9c7d8.png)

**Comment by pypper** [comment]
We merged, friends.

GG
