### ISSUE TITLE
Off by one error with mixin

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/block-explorer#8]
Hiya,

The blockchain explorer appears to show an incorrect mixin value. For example, [this](https://blocks.turtle.link/?hash=30df0abb1b5c0b953abb5530cbe86f13bd7fc1d1ae514bc78ba77835adf24a98#blockchain_transaction) transaction was sent with a mixin of 3, but it shows as "Mixin count: 4".

I have tried sending transactions via both walletlegacy and walletgreen, so I assume it's a bug in the explorer rather than the wallets.

**Comment by RocksteadyTC** [comment]
I think it is because when you specify a mixin in your wallet it is you + mixed parties, so 1 + 3
